// Code generated by hertz generator.

package permission

import (
	"context"
	"files/pkg/hertz/biz/handler"
	"files/pkg/hertz/biz/handler/handle_func"
	permission "files/pkg/hertz/biz/model/api/permission"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetPermissionMethod .
// @router /api/permission/*path [GET]
func GetPermissionMethod(ctx context.Context, c *app.RequestContext) {
	resp := new(permission.GetPermissionResp)
	handler.CommonConvert(c, handle_func.MonkeyHandle(handle_func.PermissionGetHandler, "/api/permission"), resp, false)
}

// PutPermissionMethod .
// @router /api/permission/*path [PUT]
func PutPermissionMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.PutPermissionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.PutPermissionResp)
	handler.CommonConvert(c, handle_func.MonkeyHandle(handle_func.PermissionPutHandler, "/api/permission"), resp, true)
}
