// Code generated by hertz generator.

package preview

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _previewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _previewmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
