// Code generated by hertz generator.

package nodes

import (
	"context"
	"files/pkg/hertz/biz/handler"
	"files/pkg/hertz/biz/handler/handle_func"
	nodes "files/pkg/hertz/biz/model/api/nodes"
	"github.com/cloudwego/hertz/pkg/app"
)

// NodesMethod .
// @router /api/nodes [GET]
func NodesMethod(ctx context.Context, c *app.RequestContext) {
	resp := new(nodes.NodesResp)
	handler.CommonConvert(c, handle_func.CommonHandle(handle_func.NodesGetHandler), resp, false)
}
