// Code generated by hertz generator.

package upload

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"files/pkg/access"
	"files/pkg/common"
	"files/pkg/drivers"
	"files/pkg/drivers/base"
	"files/pkg/drivers/sync/seahub"
	"files/pkg/drivers/sync/seahub/searpc"
	"files/pkg/hertz/biz/handler"
	upload "files/pkg/hertz/biz/model/upload"
	"files/pkg/models"
	"files/pkg/tasks"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"path/filepath"
	"reflect"
	"strings"
	"syscall"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"k8s.io/klog/v2"
)

// newFileHandler is a seam over the global driver adaptor so the upload
// handlers' error mapping (e.g. ErrSyncPermissionDenied -> 403) can be
// unit-tested without a live backend. Tests override it and restore in
// t.Cleanup.
var newFileHandler = func(fileType string, hp *base.HandlerParam) base.Execute {
	return drivers.Adaptor.NewFileHandler(fileType, hp)
}

func isExternalMountUnavailable(err error) bool {
	return err != nil && err.Error() == common.ErrorMessageExternalMountUnavailable
}

// UploadLinkMethod .
// @router /upload/upload_link [GET]
func UploadLinkMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.UploadLinkReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var uploadArg = &models.FileUploadArgs{
		FileParam: &models.FileParam{},
		Node:      c.Param("node"),
		From:      req.From,
		Share:     req.Share,
		ShareType: req.Sharetype,
		ShareBy:   req.Shareby,
	}
	if req.TotalSize != nil {
		uploadArg.TotalSize = *req.TotalSize
	}

	p := req.FilePath
	if !strings.HasSuffix(p, "/") {
		p = p + "/"
	}

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	fileParam, err := models.CreateFileParam(owner, p)
	if err != nil {
		klog.Errorf("file param error: %v, owner: %s", err, owner)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
		return
	}

	uploadArg.FileParam = fileParam

	// Authorize once per upload session here: the chunk POSTs that
	// follow carry the uid issued by this link, so a single gate at the
	// session-creation point covers the whole upload without re-checking
	// (which for sync would mean a seahub RPC per chunk). Share uploads
	// (share=1) are vetted by ShareMiddleware / ShareUpload; we still
	// require the internal token so a forged share=1 cannot skip the gate.
	if req.Share == "1" {
		if !handler.RequireInternalShareToken(c, "upload") {
			return
		}
	} else {
		if lvl, aerr := access.CheckAccessParam(ctx, fileParam.Owner, fileParam); aerr != nil || !lvl.Allow(models.ActionUpload) {
			klog.Warningf("[upload] permission denied: owner=%s, type=%s, path=%s, level=%v, err=%v",
				fileParam.Owner, fileParam.FileType, fileParam.Path, lvl, aerr)
			c.AbortWithStatusJSON(consts.StatusForbidden, utils.H{"error": common.ErrorMessagePermissionDenied})
			return
		}
	}

	var handlerParam = &base.HandlerParam{
		Ctx:   ctx,
		Owner: uploadArg.FileParam.Owner,
	}
	var fileHandler = newFileHandler(uploadArg.FileParam.FileType, handlerParam)
	if fileHandler == nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("handler not found, type: %s", uploadArg.FileParam.FileType)})
		return
	}
	resp, err := fileHandler.UploadLink(uploadArg)
	if err != nil {
		if errors.Is(err, seahub.ErrSyncPermissionDenied) {
			handler.RespForbidden(c, common.ErrorMessagePermissionDenied)
			return
		}
		if isExternalMountUnavailable(err) {
			c.AbortWithStatusJSON(consts.StatusServiceUnavailable, utils.H{
				"code":    1,
				"message": err.Error(),
			})
			return
		}
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{
			"code":    1,
			"message": err.Error(),
		})
		return
	}
	c.String(consts.StatusOK, string(resp))
}

// UploadedBytesMethod .
// @router /upload/file_uploaded_bytes [GET]
func UploadedBytesMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.UploadedBytesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var uploadArg = &models.FileUploadArgs{
		FileParam:     &models.FileParam{},
		Node:          c.Param("node"),
		Share:         req.Share,
		ShareType:     req.Sharetype,
		FileName:      req.FileName,
		UserAgentHash: common.Md5String(string(c.GetHeader("User-Agent"))),
	}

	p := req.ParentDir
	if !strings.HasSuffix(p, "/") {
		p = p + "/"
	}

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	// Mirror UploadLinkMethod: a share=1 request is trusted only when it
	// carries the internal token set by the share proxy.
	if req.Share == "1" {
		if !handler.RequireInternalShareToken(c, "upload") {
			return
		}
	}

	uploadArg.FileParam, err = models.CreateFileParam(owner, p)
	if err != nil {
		klog.Errorf("file param error: %v, owner: %s", err, owner)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
		return
	}

	var handlerParam = &base.HandlerParam{
		Ctx:   ctx,
		Owner: uploadArg.FileParam.Owner,
	}
	var fileHandler = newFileHandler(uploadArg.FileParam.FileType, handlerParam)
	if fileHandler == nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("handler not found, type: %s", uploadArg.FileParam.FileType)})
		return
	}
	respBytes, err := fileHandler.UploadedBytes(uploadArg)
	if err != nil {
		if errors.Is(err, seahub.ErrSyncPermissionDenied) {
			handler.RespForbidden(c, common.ErrorMessagePermissionDenied)
			return
		}
		if isExternalMountUnavailable(err) {
			c.AbortWithStatusJSON(consts.StatusServiceUnavailable, utils.H{"error": err.Error()})
			return
		}
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	resp := new(upload.UploadedBytesResp)
	if !handler.DecodeResponse(c, respBytes, resp) {
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// UploadChunksMethod .
// @router /upload/upload-link/:uid [POST]
func UploadChunksMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.UploadChunksReq

	err = c.BindAndValidate(&req)
	if err != nil {
		klog.Errorf("bind and validate error: %v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}
	req.RetJson = 1

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	klog.Infof("Posix uploadChunks, owner: %s, share: %s, shareby: %s, parentDir: %s", owner, req.Share, req.Shareby, req.ParentDir)

	var uploadArg = &models.FileUploadArgs{
		FileParam:      &models.FileParam{},
		Node:           c.Param("node"),
		UploadId:       c.Param("uid"),
		UserAgentHash:  common.Md5String(string(c.GetHeader("User-Agent"))),
		RequestContext: c,
	}

	uploadArg.ChunkInfo = new(models.ResumableInfo)
	err = json.Unmarshal(common.ToBytes(req), &uploadArg.ChunkInfo)
	if err != nil {
		klog.Errorf("Parse to upload arg error: %v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "parse to upload arg error"})
		return
	}

	header, err := c.FormFile("file")
	if err != nil {
		klog.Errorf("uploadID:%s, Failed to parse file: %v\n", uploadArg.UploadId, err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "param invalid"})
		return
	}

	uploadArg.ChunkInfo.Share = req.Share
	uploadArg.ChunkInfo.Shareby = req.Shareby
	uploadArg.ChunkInfo.SharebyPath = string(c.FormValue("sharebyPath"))
	uploadArg.ChunkInfo.File = header

	p := uploadArg.ChunkInfo.ParentDir
	if p == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "path invalid"})
		return
	}

	uploadArg.Ranges = string(c.GetHeader("Content-Range"))
	if !strings.HasSuffix(p, "/") {
		p = p + "/"
	}

	uploadArg.FileParam, err = models.CreateFileParam(owner, p)
	if err != nil {
		klog.Errorf("file param error: %v, owner: %s", err, owner)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
		return
	}

	var handlerParam = &base.HandlerParam{
		Ctx:   ctx,
		Owner: uploadArg.FileParam.Owner,
	}
	var fileHandler = newFileHandler(uploadArg.FileParam.FileType, handlerParam)
	if fileHandler == nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("handler not found, type: %s", uploadArg.FileParam.FileType)})
		return
	}
	respBytes, err := fileHandler.UploadChunks(uploadArg)
	if err != nil {
		if isExternalMountUnavailable(err) {
			c.AbortWithStatusJSON(consts.StatusServiceUnavailable, utils.H{"error": err.Error()})
			return
		}
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	resp := new(upload.UploadChunksResp)
	klog.Infof("req.ResumableChunksNumber=%d, req.ResumableTotalChunks=%d", req.ResumableChunkNumber, req.ResumableTotalChunks)
	if req.ResumableChunkNumber == req.ResumableTotalChunks {
		resp.Success = nil
		resp.Items = make([]*upload.UploadChunksFileItem, 0)
		if !handler.DecodeResponse(c, respBytes, &resp.Items) {
			return
		}
	} else {
		resp.Items = nil
		resp.Success = new(upload.UploadChunksSuccess)
		if !handler.DecodeResponse(c, respBytes, &resp.Success) {
			return
		}
	}
	c.JSON(consts.StatusOK, Coalesce(resp.Success, resp.Items))
}

func Coalesce(vals ...interface{}) interface{} {
	for _, v := range vals {
		if val := reflect.ValueOf(v); !isNil(val) {
			if val.Kind() != reflect.Ptr && val.Kind() != reflect.Interface {
				return v
			}
			if !val.IsNil() {
				return v
			}
		}
	}
	return nil
}

func isNil(val reflect.Value) bool {
	switch val.Kind() {
	case reflect.Ptr, reflect.Interface, reflect.Map, reflect.Slice, reflect.Chan, reflect.Func:
		return val.IsNil()
	default:
		return false
	}
}

func isConnectionResetError(err error) bool {
	if opErr, ok := err.(*net.OpError); ok {
		return opErr.Err == syscall.ECONNRESET
	}

	if err == syscall.ECONNRESET {
		return true
	}

	if err != nil {
		return strings.Contains(err.Error(), "connection reset")
	}

	return false
}

// SyncUploadChunksMethod .
// @router /seafhttp/:upload/:uid [POST]
func SyncUploadChunksMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var requestPath = string(c.Request.RequestURI())
	var uploadReq upload.UploadChunksReq

	err = c.BindAndValidate(&uploadReq)
	if err != nil {
		klog.Errorf("Sync uploadChunks, bind and validate error: %v", err)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	uploadPath := uploadReq.ParentDir
	if !strings.HasSuffix(uploadPath, "/") {
		uploadPath = uploadPath + "/"
	}

	var uploadType = c.Param("upload")
	var uid = c.Param("uid")
	var originalUid = uid
	if v, ok := seahub.GetAccessToken(uid); ok && v != "" {
		uid = v
		klog.V(4).Infof("[upload] Sync uploadChunks, using cached access token (path=%s, owner=%s)", requestPath, owner)
	}

	// For the last chunk of a large sync file, defer the seafile proxy
	// call to an async task so the HTTP response returns before the
	// platform proxy timeout fires.
	isLastChunk := uploadReq.ResumableChunkNumber == uploadReq.ResumableTotalChunks
	if isLastChunk && uploadReq.ResumableTotalSize >= common.AsyncFinalizeThreshold {
		bodyBytes := make([]byte, len(c.Request.Body()))
		copy(bodyBytes, c.Request.Body())

		headers := make(map[string]string)
		c.Request.Header.VisitAll(func(key, value []byte) {
			headers[string(key)] = string(value)
		})
		headers[common.REQUEST_HEADER_OWNER] = owner

		p := "/" + filepath.Join(uploadReq.DriveType, uploadReq.RepoId, strings.Trim(uploadReq.ParentDir, "/"), uploadReq.ResumableRelativePath)
		fileParam, fpErr := models.CreateFileParam(owner, p)
		if fpErr != nil {
			klog.Errorf("Sync uploadChunks, create file param error: %v", fpErr)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", fpErr)})
			return
		}

		displayParam := fileParam
		if uploadReq.Share != "" {
			sharebyPath := string(c.FormValue("sharebyPath"))
			if sharebyPath != "" {
				sharePath := sharebyPath + uploadReq.ResumableRelativePath
				if sp, spErr := models.CreateFileParam(owner, sharePath); spErr == nil {
					displayParam = sp
				}
			}
		}
		uploadParam := &models.PasteParam{
			Owner:  owner,
			Action: common.ActionUploadFinalize,
			Src:    displayParam,
			Dst:    displayParam,
		}
		task := tasks.TaskManager.CreateTask(uploadParam)
		task.SetTotalSize(uploadReq.ResumableTotalSize)
		task.ExecuteAsync(task.UploadFinalizeSync(&tasks.SyncFinalizeParams{
			BodyBytes:   bodyBytes,
			Headers:     headers,
			UploadType:  uploadType,
			UID:         uid,
			OriginalUID: originalUid,
			Owner:       owner,
			UploadReq: tasks.SyncFinalizeUploadReq{
				DriveType:         uploadReq.DriveType,
				RepoId:            uploadReq.RepoId,
				ParentDir:         uploadReq.ParentDir,
				ResumableFilename: uploadReq.ResumableFilename,
			},
		}))

		taskId := task.Id()
		klog.Infof("Sync uploadChunks, large file (%d bytes), async finalize task: %s", uploadReq.ResumableTotalSize, taskId)

		type syncFinalizeItem struct {
			Name   string `json:"name"`
			Size   int64  `json:"size"`
			TaskId string `json:"taskId"`
		}
		c.JSON(consts.StatusOK, []syncFinalizeItem{{
			Name:   uploadReq.ResumableFilename,
			Size:   uploadReq.ResumableTotalSize,
			TaskId: taskId,
		}})
		return
	}

	var executeRequest = func(uid string) (*http.Response, error) {
		reqUrl := fmt.Sprintf("http://seafile:8082/%s/%s?ret-json=1", uploadType, uid)
		klog.Infof("Sync uploadChunks, path: %s, owner: %s, uploadPath: %s", requestPath, owner, uploadPath)

		req, _ := http.NewRequest(http.MethodPost, reqUrl, bytes.NewReader(c.Request.Body()))

		c.Request.Header.VisitAll(func(key, value []byte) {
			req.Header.Set(string(key), string(value))
		})
		if req.Header.Get("Content-Disposition") == "" {
			req.Header.Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"", url.PathEscape(uploadReq.ResumableFilename)))
		}
		req.Header.Set(common.REQUEST_HEADER_OWNER, owner)
		req.ContentLength = int64(len(c.Request.Body()))

		return http.DefaultClient.Do(req)
	}

	resp, err := executeRequest(uid)
	if resp != nil {
		defer resp.Body.Close()
	}

	if err != nil || (resp != nil && resp.StatusCode != http.StatusOK) {
		retryNeeded := false
		var errMsg *models.SyncUploadError
		if err != nil {
			retryNeeded = isConnectionResetError(err)
		} else {
			bodyRes, _ := io.ReadAll(resp.Body)
			_ = json.Unmarshal(bodyRes, &errMsg)
			retryNeeded = (errMsg != nil && errMsg.Error == "Access token not found.")
		}

		if retryNeeded {
			p := "/" + filepath.Join(uploadReq.DriveType, uploadReq.RepoId, strings.Trim(uploadReq.ParentDir, "/")) + "/"
			fileParam, err := models.CreateFileParam(owner, p)
			if err != nil {
				klog.Errorf("file param error: %v, owner: %s", err, owner)
				c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
				return
			}
			newUid, refreshErr := seahub.GetUploadLink(fileParam, "web", false, true)
			if refreshErr == nil {
				seahub.SetAccessToken(originalUid, newUid)
				klog.V(4).Infof("[upload] Sync uploadChunks, refreshed access token (owner=%s, path=%s)", owner, requestPath)

				resp, err = executeRequest(newUid)
				if resp != nil {
					defer resp.Body.Close()
				}
				if err == nil && resp.StatusCode == http.StatusOK {
					klog.Infof("Sync uploadChunks: retry succeeded after token refresh (owner=%s, path=%s)", owner, requestPath)
				}
				if err != nil {
					seahub.DeleteAccessToken(originalUid)
					klog.Errorf("Sync uploadChunks, redirect error: %v", err)
					c.String(http.StatusBadRequest, searpc.SyncConnectionFailedError(err).Error())
					return
				}
			} else {
				seahub.DeleteAccessToken(originalUid)
				klog.Errorf("Token refresh failed: %v", refreshErr)
				c.AbortWithStatusJSON(http.StatusForbidden, utils.H{"error": "Access token refresh failed"})
				return
			}
		} else {
			seahub.DeleteAccessToken(originalUid)
			klog.Errorf("Sync uploadChunks, redirect error: %v", err)
			if err == nil {
				// errMsg.Error is a runtime string; passing it as
				// a format would interpret stray %-directives.
				err = fmt.Errorf("%s", errMsg.Error)
			}
			c.String(http.StatusBadRequest, searpc.SyncConnectionFailedError(err).Error())
			return
		}
	}

	if resp.StatusCode != http.StatusOK {
		bodyRes, err := io.ReadAll(resp.Body)
		if err != nil {
			c.String(resp.StatusCode, err.Error())
			return
		}
		klog.Errorf("Sync uploadChunks, proxy error: %v", string(bodyRes))
		var errMsg *models.SyncUploadError
		if err = json.Unmarshal(bodyRes, &errMsg); err != nil {
			c.String(resp.StatusCode, err.Error())
			return
		} else {
			c.String(resp.StatusCode, errMsg.Error)
		}

		return
	}

	for k, vv := range resp.Header {
		for _, v := range vv {
			c.Header(k, v)
		}
	}

	bodyRes, err := io.ReadAll(resp.Body)
	if err != nil {
		klog.Errorf("Sync uploadChunks, read resp error: %v", err)
		c.String(http.StatusBadRequest, err.Error())
		return
	}

	result := new(upload.UploadChunksResp)
	if isLastChunk {
		result.Success = nil
		result.Items = make([]*upload.UploadChunksFileItem, 0)
		if err = json.Unmarshal(bodyRes, &result.Items); err != nil {
			klog.Errorf("Sync uploadChunks, failed to unmarshal response body: %v", err)
			c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": "Failed to unmarshal response body"})
			return
		}
		seahub.DeleteAccessToken(originalUid)
	} else {
		result.Items = nil
		result.Success = new(upload.UploadChunksSuccess)
		if err = json.Unmarshal(bodyRes, &result.Success); err != nil {
			klog.Errorf("Sync uploadChunks, failed to unmarshal response body: %v", err)
			c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": "Failed to unmarshal response body"})
			return
		}
	}

	c.JSON(consts.StatusOK, Coalesce(result.Success, result.Items))
}
