// Code generated by hertz generator.

package tree

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _treeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _treemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
