// Code generated by hertz generator.

package media

import (
	"context"
	_ "files/pkg/hertz/biz/model/api/media"
	"files/pkg/media/service"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCustomPlayController .
// @router /videos/*node/*path [GET]
func GetCustomPlayController(ctx context.Context, c *app.RequestContext) {
	service.GetCustomPlayController().Play(ctx, c)
}

// GetMasterHlsVideoPlaylist .
// @router /videos/master.m3u8 [GET]
func GetMasterHlsVideoPlaylist(ctx context.Context, c *app.RequestContext) {
	service.GetDynamicHlsController().GetMasterHlsVideoPlaylist(ctx, c)
}

// GetVariantHlsVideoPlaylist .
// @router /videos/*node/main.m3u8 [GET]
func GetVariantHlsVideoPlaylist(ctx context.Context, c *app.RequestContext) {
	service.GetDynamicHlsController().GetVariantHlsVideoPlaylist(ctx, c)
}

// GetHlsVideoSegment .
// @router /videos/*node/hls1/*playlistId/*segentId.*container/*path [GET]
func GetHlsVideoSegment(ctx context.Context, c *app.RequestContext) {
	service.GetDynamicHlsController().GetHlsVideoSegment(ctx, c)
}

// GetNamedConfig .
// @router /System/Configuration/*key [GET]
func GetNamedConfig(ctx context.Context, c *app.RequestContext) {
	service.GetConfigurationController().GetNamedConfiguration(ctx, c)
}

// UpdateNamedConfig .
// @router /System/Configuration/*key [POST]
func UpdateNamedConfig(ctx context.Context, c *app.RequestContext) {
	service.GetConfigurationController().UpdateNamedConfiguration(ctx, c)
}
