// Code generated by hertz generator.

package md5

import (
	"context"
	"files/pkg/hertz/biz/handler"
	md5 "files/pkg/hertz/biz/model/api/md5"
	"github.com/cloudwego/hertz/pkg/app"
)

// Md5Method .
// @router /api/md5/*path [GET]
func Md5Method(ctx context.Context, c *app.RequestContext) {
	resp := new(md5.Md5Resp)
	handler.CommonConvert(c, handler.MonkeyHandle(handler.Md5Handler, "/api/md5"), resp, false)
}
