// Code generated by hertz generator.

package paste

import (
	"context"
	"files/pkg/common"
	"files/pkg/drivers"
	"files/pkg/drivers/base"
	"files/pkg/drivers/precheck"
	bizhandler "files/pkg/hertz/biz/handler"
	"files/pkg/models"
	"files/pkg/tasks"
	"fmt"
	"strconv"

	"github.com/cloudwego/hertz/pkg/common/utils"
	"k8s.io/klog/v2"

	paste "files/pkg/hertz/biz/model/api/paste"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PasteMethod .
// @router /api/paste/:node/ [PATCH]
func PasteMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.PasteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var owner = string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	src, err := models.CreateFileParam(owner, req.Source)
	if err != nil {
		klog.Errorf("file param error: %v, owner: %s", err, owner)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
		return
	}

	dst, err := models.CreateFileParam(owner, req.Destination)
	if err != nil {
		klog.Errorf("file param error: %v, owner: %s", err, owner)
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("file param error: %v", err)})
		return
	}

	// Share==1 means SrcOwner / DstOwner / SrcSharePath / DstSharePath
	// in the request body have *already* been resolved server-side by
	// proxySharePaste. We refuse to take those fields from anyone else;
	// otherwise a caller could paste from / to another user's drive by
	// just setting Share=1 with crafted owner fields. The proxy attaches
	// HeaderInternalShareToken to mark the forward as trusted.
	if req.Share == 1 {
		got := string(c.GetHeader(common.HeaderInternalShareToken))
		if !common.EqualInternalShareToken(got) {
			klog.Warningf("[paste] reject Share=1 request from %s without valid internal token (owner=%s)",
				c.RemoteAddr(), owner)
			c.AbortWithStatusJSON(consts.StatusForbidden, utils.H{"error": "share paste must go through the share proxy"})
			return
		}
	}

	var pasteParam = &models.PasteParam{
		Owner:        owner,
		Action:       req.Action,
		Src:          src,
		Dst:          dst,
		Share:        int(req.Share),
		SrcShareType: req.SrcShareType,
		DstShareType: req.DstShareType,
		SrcOwner:     req.SrcOwner,
		DstOwner:     req.DstOwner,
	}

	if pasteParam.Share == 1 {
		srcShareParam, err := models.CreateFileParam(req.SrcOwner, req.SrcSharePath)
		if err != nil {
			klog.Errorf("file param error: %v, owner: %s", err, owner)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("src share file param error: %v", err)})
			return
		}
		pasteParam.SrcSharePath = srcShareParam

		dstShareParam, err := models.CreateFileParam(req.DstOwner, req.DstSharePath)
		if err != nil {
			klog.Errorf("file param error: %v, owner: %s", err, owner)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("dst share file param error: %v", err)})
			return
		}
		pasteParam.DstSharePath = dstShareParam

	}

	// Verify the source actually exists on its backend BEFORE we
	// allocate a task id. Otherwise callers silently get a Completed
	// task with zero bytes (cross-node DownloadFromFiles, sync->sync
	// via GetFromSyncFileCount) or a "running -> failed" flicker
	// (rsync / rclone), neither of which is debuggable from the
	// client. Whether the failure is "really not there" or
	// "unreachable for now", the user-facing outcome is identical --
	// the paste can't proceed -- so we collapse to a single 500 with
	// a stable, FE-friendly message and keep the raw Go error in the
	// log for ops.
	if err = precheck.SourceExists(pasteParam); err != nil {
		klog.Warningf("[paste] source precheck failed: %v, owner: %s, action: %s, src: %s",
			err, owner, req.Action, req.Source)
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": common.ErrorMessagePasteSrcNotExists})
		return
	}

	// Dst-side counterpart to SourceExists: catches no-write-permission
	// before a task is allocated so the failure surfaces in this HTTP
	// response instead of an async task status. 403 + the shared
	// Permission denied message mirror other no-permission paths.
	if err = precheck.DestinationWritable(pasteParam); err != nil {
		klog.Warningf("[paste] destination precheck failed: %v, owner: %s, action: %s, dst: %s",
			err, owner, req.Action, req.Destination)
		c.AbortWithStatusJSON(consts.StatusForbidden, utils.H{"error": common.ErrorMessagePermissionDenied})
		return
	}

	handler := drivers.Adaptor.NewFileHandler(pasteParam.Src.FileType, &base.HandlerParam{})

	task, err := handler.Paste(pasteParam)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{
			"code":    1,
			"message": err.Error(),
		})
		return
	}

	c.SetStatusCode(consts.StatusOK)
	var res = map[string]string{"task_id": task.Id()}

	resp := new(paste.PasteResp)
	if !bizhandler.DecodeResponse(c, common.ToBytes(res), resp) {
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// GetTaskMethod .
// @router /api/task/:node/ [GET]
func GetTaskMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.GetTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var owner = string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	status := ""
	if req.Status != nil {
		status = *req.Status
	}
	tasks := tasks.TaskManager.GetTask(owner, req.TaskId, status)
	var res = make(map[string]interface{})
	res["code"] = 0
	res["msg"] = "success"

	if req.TaskId == "" {
		res["tasks"] = tasks
	} else {
		if len(tasks) > 0 {
			res["task"] = tasks[0]
		} else {
			res["task"] = tasks
		}
	}

	klog.Infof("Task - id: %s, status: %s, res: %s", req.TaskId, status, common.ToJson(res))

	resp := new(paste.GetTaskResp)
	if !bizhandler.DecodeResponse(c, common.ToBytes(res), resp) {
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// DeleteTaskMethod .
// @router /api/task/:node/ [DELETE]
func DeleteTaskMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.DeleteTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var owner = string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	all := ""
	if req.All != nil {
		all = strconv.Itoa(int(*req.All))
	}

	tasks.TaskManager.CancelTask(owner, req.TaskId, all)

	var res = map[string]interface{}{
		"code": 0,
		"msg":  "success",
	}

	resp := new(paste.DeleteTaskResp)
	if !bizhandler.DecodeResponse(c, common.ToBytes(res), resp) {
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// PauseResumeTaskMethod .
// @router /api/task/:node/ [POST]
func PauseResumeTaskMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.PauseResumeTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	var owner = string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}
	if req.Op == "pause" {
		tasks.TaskManager.PauseTask(owner, req.TaskId)
	} else {
		tasks.TaskManager.ResumeTask(owner, req.TaskId)
	}

	var res = map[string]interface{}{
		"code": 0,
		"msg":  "success",
	}

	resp := new(paste.PauseResumeTaskResp)
	if !bizhandler.DecodeResponse(c, common.ToBytes(res), resp) {
		return
	}
	c.JSON(consts.StatusOK, resp)
}
