// Code generated by hertz generator.

package paste

import (
	"context"
	"encoding/json"
	"files/pkg/hertz/biz/handler/handle_func"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"k8s.io/klog/v2"

	paste "files/pkg/hertz/biz/model/api/paste"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PasteMethod .
// @router /api/paste/*node [PATCH]
func PasteMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.PasteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(paste.PasteResp)
	respBytes := handle_func.PasteHandle(ctx, c, req, "/api/paste")
	if respBytes != nil {
		if err := json.Unmarshal(respBytes, &resp); err != nil {
			klog.Errorf("Failed to unmarshal response body: %v", err)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "Failed to unmarshal response body"})
			return
		}
		c.JSON(consts.StatusOK, resp)
	}
}

// GetTaskMethod .
// @router /api/task/*node [GET]
func GetTaskMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.GetTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(paste.GetTaskResp)
	respBytes := handle_func.TaskHandle(ctx, c, req, "/api/task")
	if respBytes != nil {
		if err := json.Unmarshal(respBytes, &resp); err != nil {
			klog.Errorf("Failed to unmarshal response body: %v", err)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "Failed to unmarshal response body"})
			return
		}
		c.JSON(consts.StatusOK, resp)
	}
}

// DeleteTaskMethod .
// @router /api/task/*node [DELETE]
func DeleteTaskMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req paste.DeleteTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(paste.DeleteTaskResp)
	respBytes := handle_func.TaskHandle(ctx, c, req, "/api/task")
	if respBytes != nil {
		if err := json.Unmarshal(respBytes, &resp); err != nil {
			klog.Errorf("Failed to unmarshal response body: %v", err)
			c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "Failed to unmarshal response body"})
			return
		}
		c.JSON(consts.StatusOK, resp)
	}
}
