// Code generated by hertz generator.

package users

import (
	"context"

	users "files/pkg/hertz/biz/model/api/users"
	"files/pkg/integration"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UsersMethod .
// @router /api/users/ [GET]
func UsersMethod(ctx context.Context, c *app.RequestContext) {
	var userData = integration.IntegrationService.GetUsers()

	resp := &users.UsersResp{
		Data: new(users.UsersData),
	}

	var usersNodes []*users.UsersNode
	for k, v := range userData {
		var u = &users.UsersNode{
			Name: k,
			Role: v,
		}
		usersNodes = append(usersNodes, u)
	}

	resp.Data.Users = usersNodes

	c.JSON(consts.StatusOK, resp)
}
