// Code generated by hertz generator.

package raw

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rawMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rawmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
