// Code generated by hertz generator.

package nodes

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodesmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodesMw() []app.HandlerFunc {
	// your code...
	return nil
}
