// Code generated by hertz generator.

package search

import (
	"context"
	"fmt"

	"files/pkg/common"
	"files/pkg/hertz/biz/dal/database"
	search "files/pkg/hertz/biz/model/api/search"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Search .
// @router /api/resources/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req search.SearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": "user not found"})
		return
	}

	result, err := database.QuerySearchSharedDirectories(owner)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": fmt.Sprintf("query shared paths error: %v", err)})
		return
	}

	_ = result

	// todo tidy result
	// todo call search service

	resp := new(search.SearchResp)

	c.JSON(consts.StatusOK, resp)
}
