// Code generated by hertz generator.

package search

import (
	"context"
	"fmt"

	"files/pkg/common"
	"files/pkg/global"
	"files/pkg/hertz/biz/dal/database"
	"files/pkg/hertz/biz/handler"
	search "files/pkg/hertz/biz/model/api/search"
	"files/pkg/models"

	"github.com/cloudwego/hertz/pkg/app"
	"k8s.io/klog/v2"
)

// GetDirectories .
// @router /api/search/get_directory/ [POST]
func GetDirectories(ctx context.Context, c *app.RequestContext) {
	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		handler.RespError(c, common.ErrorMessageOwnerNotFound)
		return
	}

	klog.Infof("[search] GetDirectories, owner: %s", owner)

	nodes := global.GlobalNode.GetNodes()

	internalShares, externalShares, err := database.QuerySearchSharedDirectories(owner)
	if err != nil {
		klog.Errorf("[search] GetDirectories, owner: %s, query shares error: %v", owner, err)
		handler.RespError(c, fmt.Sprintf("Query Shares Error: %v", err))
		return
	}

	var result []*search.DirectoryInfo
	for _, s := range internalShares {
		var di = &search.DirectoryInfo{
			Path:       fmt.Sprintf("/share/%s/", s.PathID),
			Permission: s.Permission,
		}
		result = append(result, di)
	}
	for _, s := range externalShares {
		var di = &search.DirectoryInfo{
			Path:       fmt.Sprintf("/share/%s/", s.ID),
			Permission: s.Permission,
		}
		result = append(result, di)
	}

	for _, n := range nodes {
		result = append(result, &search.DirectoryInfo{
			Path:       fmt.Sprintf("/cache/%s/", n.Name),
			Permission: 4,
		}, &search.DirectoryInfo{
			Path:       fmt.Sprintf("/external/%s/", n.Name),
			Permission: 4,
		})
	}

	result = append(result,
		&search.DirectoryInfo{
			Path:       "/drive/Home/",
			Permission: 4,
		},
		&search.DirectoryInfo{
			Path:       "/drive/Data/",
			Permission: 4,
		},
	)

	klog.Infof("[search] GetDirectories, owner: %s, result: %v", owner, common.ParseString(result))

	handler.RespSuccess(c, result)
}

// CheckDirectory .
// @router /api/search/check_directory/*path [POST]
func CheckDirectory(ctx context.Context, c *app.RequestContext) {
	var sharePath = c.Param("path")

	owner := string(c.GetHeader(common.REQUEST_HEADER_OWNER))
	if owner == "" {
		handler.RespError(c, common.ErrorMessageOwnerNotFound)
		return
	}

	fileParam, err := models.CreateFileParam(owner, sharePath)
	if err != nil {
		handler.RespError(c, common.ErrorMessagePathInvalid)
		return
	}

	var shareId = fileParam.Extend

	var permission int32
	if fileParam.FileType == common.Share {
		shared, err := database.GetSharePath(shareId)
		if err != nil {
			klog.Errorf("[search] CheckDirectory, get share failed, owner: %s, error: %v", owner, err)
			handler.RespError(c, fmt.Sprintf("Check Directory Error: %v", err))
			return
		}

		if shared == nil {
			handler.RespSuccess(c, nil)
			return
		}
		member, err := database.GetShareMember(shared.ID, owner)
		if err != nil {
			klog.Errorf("[search] CheckDirectory, get member failed, owner: %s, error: %v", owner, err)
			handler.RespError(c, fmt.Sprintf("Check Directory Error: %v", err))
			return
		}

		if member == nil {
			permission = 0
		} else {
			permission = member.Permission
		}
	}

	var result = &search.DirectoryInfo{
		Path:       sharePath,
		Permission: permission,
	}

	handler.RespSuccess(c, result)
}
