// Code generated by hertz generator.

package callback

import (
	"context"
	"files/pkg/drivers/sync/seahub"
	"files/pkg/hertz/biz/handler/api/share"
	"strings"

	"github.com/cloudwego/hertz/pkg/common/utils"
	"k8s.io/klog/v2"

	callback "files/pkg/hertz/biz/model/callback"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CallbackCreateMethod .
// @router /callback/create [POST]
func CallbackCreateMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req callback.CallbackCreateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	bflName := strings.TrimSpace(req.Name)
	err = seahub.HandleCallbackCreate(bflName)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	resp := new(callback.CallbackCreateResp)
	c.JSON(consts.StatusOK, resp)
}

// CallbackDeleteMethod .
// @router /callback/delete [POST]
func CallbackDeleteMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req callback.CallbackDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusBadRequest, utils.H{"error": err.Error()})
		return
	}

	bflName := strings.TrimSpace(req.Name)

	err = share.RemoveUserRelativeAdjustShare(bflName, nil)
	if err != nil {
		klog.Errorf("Delete user relative adjust share for %s failed: %v", bflName, err)
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	err = seahub.HandleCallbackDelete(bflName)
	if err != nil {
		c.AbortWithStatusJSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	resp := new(callback.CallbackDeleteResp)
	c.JSON(consts.StatusOK, resp)
}
