// Code generated by hertz generator.

package paste

import (
	bizhandler "files/pkg/hertz/biz/handler"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pasteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pastemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskdeletemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskgetmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodeMw() []app.HandlerFunc  { return []app.HandlerFunc{bizhandler.NodeGuard()} }
func _node0Mw() []app.HandlerFunc { return []app.HandlerFunc{bizhandler.NodeGuard()} }

func _pauseresumetaskmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
