// Code generated by hertz generator.

package search

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getauthoritydirectoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkcheckdirectoryauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authorityMw() []app.HandlerFunc {
	// your code...
	return nil
}
