// Code generated by hertz generator.

package raw

import (
	"context"
	"files/pkg/hertz/biz/handler"
	http2 "files/pkg/http"

	"github.com/cloudwego/hertz/pkg/app"
)

// RawMethod .
// @router /api/raw/*path [GET]
func RawMethod(ctx context.Context, c *app.RequestContext) {
	handler.StraightForward(c, http2.WrapperRawArgs(http2.RawHandler, "/api/raw/"))
}
