// Code generated by hertz generator.

package media

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configurationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnamedconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenamedconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcustomplaycontrollerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hls1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethlsvideosegmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmasterhlsvideoplaylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvarianthlsvideoplaylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playlistidMw() []app.HandlerFunc {
	// your code...
	return nil
}
