// Code generated by hertz generator.

package callback

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callbackcreatemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callbackdeletemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callbackconnectmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
