// Code generated by hertz generator.

package permission

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _permissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpermissionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putpermissionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
