// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api_external "files/pkg/hertz/biz/router/api/external"
	api_md5 "files/pkg/hertz/biz/router/api/md5"
	api_media "files/pkg/hertz/biz/router/api/media"
	api_nodes "files/pkg/hertz/biz/router/api/nodes"
	api_paste "files/pkg/hertz/biz/router/api/paste"
	api_permission "files/pkg/hertz/biz/router/api/permission"
	api_preview "files/pkg/hertz/biz/router/api/preview"
	api_raw "files/pkg/hertz/biz/router/api/raw"
	api_repos "files/pkg/hertz/biz/router/api/repos"
	api_resources "files/pkg/hertz/biz/router/api/resources"
	api_search "files/pkg/hertz/biz/router/api/search"
	api_share "files/pkg/hertz/biz/router/api/share"
	api_tree "files/pkg/hertz/biz/router/api/tree"
	api_users "files/pkg/hertz/biz/router/api/users"
	callback "files/pkg/hertz/biz/router/callback"
	upload "files/pkg/hertz/biz/router/upload"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_media.Register(r)

	api_search.Register(r)

	api_users.Register(r)

	api_share.Register(r)

	callback.Register(r)

	api_permission.Register(r)

	api_md5.Register(r)

	api_external.Register(r)

	api_paste.Register(r)

	api_raw.Register(r)

	api_preview.Register(r)

	api_tree.Register(r)

	api_resources.Register(r)

	api_repos.Register(r)

	api_nodes.Register(r)

	upload.Register(r)
}
