// Code generated by hertz generator.

package share

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shareMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _share_memberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removesharememberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsharememberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addsharememberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesharememberpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _share_pathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsharepathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _node0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesharepathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsharepathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _share_tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _node1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokesharetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsharetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatesharetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesharepathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_shareMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsharepathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}
