// Code generated by hertz generator.

package preview

import (
	"context"
	"files/pkg/hertz/biz/handler"
	"files/pkg/hertz/biz/handler/handle_func"
	preview "files/pkg/hertz/biz/model/api/preview"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PreviewMethod .
// @router /api/preview/*path [GET]
func PreviewMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req preview.PreviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	handler.StraightForward(c, handle_func.WrapperPreviewArgs(handle_func.PreviewHandler, "/api/preview/"))

}
