name: Publish to Dockerhub ( seahub-init )

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
#  push:
#    branches:
#      - "main"
#      - "go_seahub_db"

jobs:
  update_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.1.0
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","style"]'
          add_label: 'true'

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: beclab/seahub-init:${{ github.event.inputs.tags }}
#          tags: beclab/seahub-init:${{ steps.get-latest-tag.outputs.tag }}
          file: Dockerfile.seahub
          platforms: linux/amd64,linux/arm64

