// Code generated by hertz generator.

package repos

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletereposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _patchreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reposMw() []app.HandlerFunc {
	// your code...
	return nil
}
