// Code generated by hertz generator.

package repos

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletereposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _patchreposmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repo_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _download_infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreposdonwloadinfomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccountinfomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
